### PR TITLE
class declaration change, syntax and minor bug fixes

### PR DESCRIPTION
**Pull request by yoav1994**
1)changed how classes are declared and inherit from one to other
2)changed word xrange to range in for loops
3)some minor bugs (not importing relevant classes, using undefined methods)

### CODE REVIEW

**Comment by Coder-DG** [comment]
Hey, can you give a more informative PR name? You can take a look at examples here: https://github.com/cloudify-cosmo/cloudify-common/pulls?q=is%3Apr+is%3Aclosed

**Comment by yoav1994** [comment]
1) changed how classes are declared and inherit from one to other
2) changed word xrange to range in for loops
3) some minor bugs (not importing relevant classes, using undefined methods)

**Comment by yoav1994** [comment]
I think that it is important (after my pull will be accepted) that people will work on improving the coding style which is quite bad in many places and makes the code very unreadable;

**Comment by Coder-DG** [comment]
> 1. changed how classes are declared and inherit from one to other
> 2. changed word xrange to range in for loops
> 3. some minor bugs (not importing relevant classes, using undefined methods)

Cool! Add it to the PR description and change the title for future reference :)

**Comment by Coder-DG** [comment]
> I think that it is important (after my pull will be accepted) that people will work on improving the coding style which is quite bad in many places and makes the code very unreadable;

That's a really great idea! I've added a wiki page and will have automated CI check with `flake8` (issue #5)

**Comment by Coder-DG** [comment]
Hi, I've committed to your branch and added a CI `flake8` check (checks PEP8 python syntax). Let's fix that and then I'll approve the PR.

You can run [flake8](http://flake8.pycqa.org/en/latest/) before pushing to make sure the format works. If you'd like me to do the formatting then let me know.

**Comment by Coder-DG** [comment]
This fixes #1 and #5

**Review by Coder-DG — APPROVED** [review]

**Comment by Coder-DG** [comment]
Approved, you can choose the Squash and merge option

**Pull request merged**
